# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('price_range', models.IntegerField(default=0)),
                ('listing_date', models.DateTimeField(verbose_name='Listing Date')),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
